name: DevSecOps Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:

  component-analysis-npm-audit:
    name: Component Analysis and NPM Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Run NPM Audit
        run: npm audit --json > npm-audit.json
        continue-on-error: true

      - name: Upload NPM Audit Report
        uses: actions/upload-artifact@v3
        with:
          name: npm-audit-report
          path: npm-audit.json

  build-dummy:
    name: Build Echo Statement
    runs-on: ubuntu-latest
    steps:
      - name: Echo Building Going on
        run: echo "Building going on"

  deploy-dummy:
    name: Deploy Echo Statement
    runs-on: ubuntu-latest
    needs: build-dummy
    steps:
      - name: Echo Deploying Going on
        run: echo "Deploying going on"

# name: Security check - Bandit

# on: push
#   build:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         os: [ ubuntu-latest, macos-latest ]
#         python-version: ['3.10.5']
#     name: Python ${{ matrix.python-version }} ${{ matrix.os }} 

#     steps:
#     - uses: actions/checkout@v2

#     - name: Security check - Bandit
#       uses: ./
#       with:
#         python_version: ${{ matrix.python-version }}
#         project_path: .
#         ignore_failure: true

#     - name: Security check report artifacts
#       uses: actions/upload-artifact@v1
#       # if: failure()
#       with:
#         name: Security report
#         path: output/security_report.txt